//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

public class AssetPath
{
	static public string GetAssetStorePath()
	{
		string dataPath = Application.dataPath;
		string assetStorePath;
		switch(Application.platform)
		{
		case RuntimePlatform.OSXEditor:
		case RuntimePlatform.WindowsEditor:
		case RuntimePlatform.LinuxPlayer:
		case RuntimePlatform.OSXPlayer:
		case RuntimePlatform.WindowsPlayer:
		case RuntimePlatform.WindowsWebPlayer:
		case RuntimePlatform.OSXWebPlayer:
			int pos = dataPath.LastIndexOf("/");
			assetStorePath = dataPath.Substring(0, pos);
			assetStorePath = assetStorePath + "/AssetBundle/PC";
			return "file:///" + assetStorePath;
		case RuntimePlatform.IPhonePlayer:
			return "file:///" + dataPath + "Raw/IOS/";
		case RuntimePlatform.Android:
			return "jar:file:///" + dataPath + "!/assets/Android";
		}

		int pos2 = dataPath.LastIndexOf("/");
		assetStorePath = dataPath.Substring(0, pos2);
		assetStorePath = assetStorePath + "/AssetBundle/PC";
		return "file:///" + assetStorePath;
	}

	static public string GetAssetStorePathWithSlash()
	{
		return GetAssetStorePath() + "/";
	}
}

