//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;
public class EffectUtility
{
	public enum FxPlayState
	{
		Loading,
		Begin,
		End,
	}

	public delegate void OnFxPlayCallBack(FxPlayParam param);
	public class FxPlayParam
	{
		public string fileName;
		public float lifeTime;
		public GameObject objFx;
		public FxPlayState state;
		public Vector3 vOffsetPos;
		public Transform transTarget;
		public object userParam;
		public OnFxPlayCallBack callBack;

		public FxPlayParam(string fxPath, float time, Transform target, Vector3 offset, object param, OnFxPlayCallBack cb)
		{
			fileName = fxPath;
			lifeTime = time;
			state = FxPlayState.Loading;
			vOffsetPos = offset;
			transTarget = target;
			userParam = param;
			callBack = cb;
		}

		public void DispatchState(FxPlayState state)
		{
			this.state = state;
			if(null != callBack)
			{
				callBack(this);
			}
		}
	}

	//
	static LinkedList<FxPlayParam> listLoading = new LinkedList<FxPlayParam>();

	/// <summary>
	/// Plaies the effect.
	/// </summary>
	static public void PlayEffect(string fxPath, float time, Transform parent)
	{
		FxPlayParam param = new FxPlayParam(fxPath, time, parent, Vector3.zero, null, null);
		OnPlayNewEffect(param);
	}

	/// <summary>
	/// Plaies the effect.
	/// </summary>
	static public void PlayEffect(string fxPath, float time, Transform parent, Vector3 vOffset)
	{
		FxPlayParam param = new FxPlayParam(fxPath, time, parent, vOffset, null, null);
		OnPlayNewEffect(param);
	}

	/// <summary>
	/// Plaies the effect.
	/// </summary>
	static public void PlayEffect(string fxPath, float time, Transform parent, object userParam, OnFxPlayCallBack cb)
	{
		FxPlayParam param = new FxPlayParam(fxPath, time, parent, Vector3.zero, userParam, cb);
		OnPlayNewEffect(param);
	}

	/// <summary>
	/// Plaies the effect.
	/// </summary>
	static public void PlayEffect(string fxPath, float time, Transform parent, Vector3 vOffset, object userParam, OnFxPlayCallBack cb)
	{
		FxPlayParam param = new FxPlayParam(fxPath, time, parent, vOffset, userParam, cb);
		OnPlayNewEffect(param);
	}

	/// <summary>
	/// Stop the effect.
	/// </summary>
	static public void DestroyEffect(FxPlayParam fx)
	{
		if(null == fx) return;
		OnEffectPlayFinished(fx);
	}

	/// <summary>
	/// Raises the play new effect event.
	/// </summary>
	static void OnPlayNewEffect(FxPlayParam param)
	{
		if(null == param) return;

		listLoading.AddLast(param);
		param.DispatchState(FxPlayState.Loading);
		EffectMgr.Instance.LoadEffect(param.fileName, OnEffectLoadCallBack, null, param);
	}

	static void RemoveEffect(FxPlayParam param)
	{
		if(null == param) return;
		if(null != param.objFx) 
		{
			GameObject.Destroy(param.objFx);
		}

		listLoading.Remove(param);
		EffectMgr.Instance.UnLoadEffect(param.fileName);
	}

	static void OnEffectLoadCallBack(string fxPath, GameObject objFx, object userParam)
	{
		FxPlayParam fx = (FxPlayParam)userParam;
		if(null == fx) return;

		fx.objFx = GameObject.Instantiate(objFx) as GameObject;
		if(null == fx.objFx)
		{
			fx.DispatchState(FxPlayState.End);
			RemoveEffect(fx);
			return;
		}

		//fx.objFx.SetActive(true);
		fx.objFx.transform.parent = fx.transTarget;
		fx.objFx.transform.localPosition = fx.vOffsetPos;
		fx.objFx.transform.localRotation = Quaternion.identity;
		fx.objFx.transform.localScale = Vector3.one;

		ParticleSystem[] cm = fx.objFx.GetComponents<ParticleSystem>();
		ParticleSystem[] child = fx.objFx.GetComponentsInChildren<ParticleSystem>();
		foreach(ParticleSystem p in cm)
		{
			p.Play();
		}
		foreach(ParticleSystem p in child)
		{
			p.Play();
		}

		if(fx.lifeTime > 0f)
		{
			TimeMgr.Instance.Exec(OnEffectPlayFinished, fx, (int)(fx.lifeTime * 1000f));
		}

		fx.DispatchState(FxPlayState.Begin);
	}

	static void OnEffectPlayFinished(object param)
	{
		FxPlayParam fx = (FxPlayParam)param;
		if(null == fx) return;

		fx.DispatchState(FxPlayState.End);
		RemoveEffect(fx);
	}

}